# Generated by Django 4.2 on 2023-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_user_tablephoto_itemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
