# Generated by Django 4.2 on 2023-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_category',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('wearables', 'Wearables'), ('consumables', 'Consumables'), ('homeables', 'Homeables'), ('gardenables', 'Gardenables'), ('entertainmentables', 'Entertainables')], default='miscellaneous'),
        ),
    ]
