# Generated by Django 4.2 on 2023-04-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_table_table_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='table',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
